server:
  port: 10000
  ip: localhost
spring:
  application:
   name: xiangyang-service-zuul
  cloud:
    sentinel: 
      transport:
        dashboard: 121.41.56.97:9999
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9797/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}

